[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]
[tool.poetry]
authors = ["ay136416 <<>>"]
description = "An open source discord bot for quizzes!"
name = "thediscordmathproblembot"
version = "0.0.2a1"
[tool.poetry.dependencies]
discord = "^1.7.3"
discord-py-slash-command = "^3.0.1"
"dislash.py" = {git = "https://github.com/EQUENOS/dislash.py.git", rev = "main"}
nextcord = {git = "https://github.com/nextcord/nextcord.git"}
python = "^3.8"
#dislash = {git = "https://github.com/EQUENOS/dislash.py.git#main"}
typing-extensions = "^3.10.0"
orjson = "^3.6.3"
#sqldict = {git = "https://github.com/rf20008/sqldict.git"}
python-dotenv = "^0.19.1"
sqldict = {git = "https://github.com/rf20008/sqldict.git", rev = "main"}
aiosqlite = "^0.17.0"
[tool.poetry.dev-dependencies]
